create table if not exists inventory_item (
    id bigint generated by default as identity primary key,
    sku varchar(64) not null,
    name varchar(128) not null,
    price numeric(12,2) not null,
    stock int not null,
    tags varchar(256),
    created_at timestamp not null default current_timestamp
);

create table if not exists customer_note (
    id bigint generated by default as identity primary key,
    customer varchar(64) not null,
    note varchar(512),
    created_at timestamp not null default current_timestamp
);
