-- lighting-config schema for Oracle 19c+
CREATE TABLE config_item (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant VARCHAR2(64) DEFAULT 'default' NOT NULL,
    namespace VARCHAR2(128) NOT NULL,
    app_id VARCHAR2(128) NOT NULL,
    key VARCHAR2(512) NOT NULL,
    content_type VARCHAR2(32) DEFAULT 'TEXT' NOT NULL,
    value CLOB NOT NULL,
    version NUMBER(19) NOT NULL,
    tags CLOB,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uq_config_item ON config_item (tenant, namespace, app_id, key);

CREATE TABLE revision (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant VARCHAR2(64) NOT NULL,
    namespace VARCHAR2(128) NOT NULL,
    app_id VARCHAR2(128) NOT NULL,
    key VARCHAR2(512) NOT NULL,
    version NUMBER(19) NOT NULL,
    op VARCHAR2(32) NOT NULL,
    operator VARCHAR2(128) NOT NULL,
    diff CLOB,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_revision_lookup ON revision (tenant, namespace, app_id, key);
