-- lighting-config schema for Oracle 19c+
CREATE TABLE config_item (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant VARCHAR2(64) DEFAULT 'default' NOT NULL,
    namespace VARCHAR2(128) NOT NULL,
    app_id VARCHAR2(128) NOT NULL,
    key VARCHAR2(512) NOT NULL,
    content_type VARCHAR2(32) DEFAULT 'TEXT' NOT NULL,
    value CLOB NOT NULL,
    version NUMBER(19) NOT NULL,
    tags CLOB,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uq_config_item ON config_item (tenant, namespace, app_id, key);

CREATE TABLE revision (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant VARCHAR2(64) NOT NULL,
    namespace VARCHAR2(128) NOT NULL,
    app_id VARCHAR2(128) NOT NULL,
    key VARCHAR2(512) NOT NULL,
    version NUMBER(19) NOT NULL,
    op VARCHAR2(32) NOT NULL,
    operator VARCHAR2(128) NOT NULL,
    diff CLOB,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_revision_lookup ON revision (tenant, namespace, app_id, key);

CREATE TABLE cache_miss_alert (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant VARCHAR2(64) NOT NULL,
    namespace VARCHAR2(128) NOT NULL,
    app_id VARCHAR2(128) NOT NULL,
    selector VARCHAR2(512) NOT NULL,
    miss_count NUMBER(19) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_cache_miss_tenant ON cache_miss_alert (tenant, created_at);

-- Sample seed data for demos
INSERT ALL
    INTO config_item (tenant, namespace, app_id, key, content_type, value, version, tags, enabled)
        VALUES ('default', 'prod', 'order-service', 'feature.pay.v2', 'TEXT', 'true', 3, TO_CLOB('{"env":"prod","owner":"fintech"}'), 1)
    INTO config_item (tenant, namespace, app_id, key, content_type, value, version, tags, enabled)
        VALUES ('default', 'prod', 'order-service', 'datasource.read', 'JSON', '{"url":"jdbc:oracle:thin:@//db:1521/order","user":"order_ro"}', 2, TO_CLOB('{"tier":"critical"}'), 1)
    INTO config_item (tenant, namespace, app_id, key, content_type, value, version, tags, enabled)
        VALUES ('default', 'beta', 'search-service', 'feature.ai.ranking', 'TEXT', 'false', 1, TO_CLOB('{"experiment":"A/B"}'), 1)
SELECT * FROM dual;

INSERT ALL
    INTO revision (tenant, namespace, app_id, key, version, op, operator, diff)
        VALUES ('default', 'prod', 'order-service', 'feature.pay.v2', 3, 'UPSERT', 'system', TO_CLOB('{"old":"false","new":"true"}'))
    INTO revision (tenant, namespace, app_id, key, version, op, operator, diff)
        VALUES ('default', 'prod', 'order-service', 'datasource.read', 2, 'UPSERT', 'dba', TO_CLOB('{"old":"jdbc:oracle:thin:@//old","new":"jdbc:oracle:thin:@//db"}'))
SELECT * FROM dual;
