server:
  port: 8082

lighting:
  config:
    client:
      tenant: default
      namespace: default
      app-id: demo-client
      poll-interval: 5s
      server:
        address: http://localhost:7086
